import Head from 'next/head'
import React from 'react'
import SignUpCard from '../../components/SignUpCard'

export default function SignUp() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <SignUpCard />
            </main>

        </div>
    )
}