import Head from 'next/head'
import React from 'react'
import NavBar from '../../components/NavBar'
import SignUpCard from '../../components/SignUpCard'

export default function Login() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <SignUpCard />
            </main>

        </div>
    )
}